---
title       : Developing Data Products Assignment
subtitle    : Major Cities in China
author      : Wenjing Liu
job         : November 22, 2018 (Updated on December 12, 2018)
framework   : io2012        # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : tomorrow      # 
widgets     : []            # {mathjax, quiz, bootstrap}
mode        : selfcontained # {standalone, draft}
knit        : slidify::knit2slides
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=FALSE)
```

##  Top 100 Largest Cities by Population in China (plotly)

```{r message=FALSE, warning=FALSE, echo=FALSE, cache=FALSE, results='asis', fig.align='center'}
library(plotly)
cities <- readRDS("D:/R/data/cn_cities.rds")
cities <- cities[1:100,]

geo <- list(
  scope = 'asia',
  projection = list(type = 'Mercator'),
  showland = TRUE,
  landcolor = toRGB("gray85"),
  countrycolor = toRGB("white"),
  subunitcolor = toRGB("white"),
  countrywidth = 1,
  subunitwidth = 1)

p <- plot_geo(cities, 
              locationmode='CHN', 
              sizes=c(1, 200)) %>% 
     add_markers(x=~lng, y=~lat, 
                 size=~sqrt(population),
                 hoverinfo="text", 
                 text=~paste(city, "<br />", population)) %>%
     layout(title='', 
            geo=geo)

htmlwidgets::saveWidget(as_widget(p), "p.html")
cat('<iframe src="./p.html" width=100% height=100% allowtransparency="true"></iframe>')
```

---
## Load data

Data Source: https://simplemaps.com/data/cn-cities

```{r}
cities <- read.csv("D:/R/data/cn_cities.csv", 
                   header=TRUE, 
                   #colClasses="character",
                   strip.white=FALSE,
                   stringsAsFactors=FALSE, 
                   na.strings=c("NA", "NaN", "N/A", "", "#VALUE!", "#DIV/0!"),
                   encoding='UTF-8')
dim(cities)
```

---

## Sort data by population size descending

```{r}
cities <- cities[order(-cities$population),]
head(cities)
```

---

## Save dataset as RDS file, use it in a Shiny app

app.R (Part 1)

```{r eval=FALSE}
library(shiny); library(leaflet)
cities <- readRDS("cn_cities.rds"); cities <- cities[1:100,]

ui <- fluidPage(
    titlePanel("Top 100 Largest Cities by Population in China"),
    sidebarLayout(
        sidebarPanel(
            strong("Display the largest cities ranked by population in China."), p(),
            em("E.g. Set the slider at value (1,10), then the top 10 largest cities will be displayed. The areas of the circles represent the relative sizes of the city populations."), p(),
            sliderInput("ui_range", 
                        label = "Range of ranks:",
                        min = 1, max = nrow(cities), value = c(1, nrow(cities)))),
    mainPanel(leafletOutput("ui_map"))))
```

---

app.R (Part 2)

```{r eval=FALSE}
server <- function(input, output, session) {
    filteredData <- reactive({cities[input$ui_range[1]:input$ui_range[2],]
    }) 
    output$ui_map <- renderLeaflet({
        cities %>% leaflet() %>% addTiles() %>% 
            fitBounds(~min(lng), ~min(lat), ~max(lng), ~max(lat))
    })
    observe({
      leafletProxy("ui_map", data=filteredData()) %>%
        clearShapes() %>%
        addCircles(weight=1, color="#49b2b2", radius=~sqrt(population)*50)
    })
}

shinyApp(ui, server)
```

---

## Deploy the app on Shinyapps.io or Github

<br>

1. You can visit the app online at https://wenjing.shinyapps.io/app-cn-cities/

2. Or launch it in your RStudio by running the following code.

```{r eval=FALSE}
library(shiny); runGitHub( "Shiny-CN_Cities", "Nov05")
```

<br>

# Thank you for reviewing the assignment!


